  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
      build: 
        context: . 
        dockerfile: Dockerfile.prod
      command: gunicorn firemageguideweb.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - static_volume:/home/app/web/static
      expose:
        - 8000
      depends_on:
        - db
      env_file:
      - ./.env.prod
    nginx:
      build: ./nginx
      volumes:
        - static_volume:/home/app/web/static
      ports:
        - 1337:80
      depends_on:
        - web
